function gp_save_statistics( prefix, stat, gt )
% save statistics as gnuplot readable file

%*****************************************************************************
% Copyright (c) 2019      Fiete Winter                                       *
%                         Institut fuer Nachrichtentechnik                   *
%                         Universitaet Rostock                               *
%                         Richard-Wagner-Strasse 31, 18119 Rostock, Germany  *
%                                                                            *
% This file is part of the supplementary material for Fiete Winter's         *
% PhD thesis                                                                 *
%                                                                            *
% You can redistribute the material and/or modify it  under the terms of the *
% GNU  General  Public  License as published by the Free Software Foundation *
% , either version 3 of the License,  or (at your option) any later version. *
%                                                                            *
% This Material is distributed in the hope that it will be useful, but       *
% WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY *
% or FITNESS FOR A PARTICULAR PURPOSE.                                       *
% See the GNU General Public License for more details.                       *
%                                                                            *
% You should  have received a copy of the GNU General Public License along   *
% with this program. If not, see <http://www.gnu.org/licenses/>.             *
%                                                                            *
% http://github.com/fietew/phd-thesis                 fiete.winter@gmail.com *
%*****************************************************************************

% save histograms
gp_save([prefix, '_hist.txt'], ...
        [stat.hist_bins; stat.hist_all; stat.hist_sub.'].',...
        ['histograms of ', prefix, '\n' ...
         '# bin centres, overall hist., histograms for each listener']); 
% save arithmetic mean
gp_save([prefix, '_mean.txt'],...
        [gt,...
        stat.mean_cond,...
        stat.mean_conf_cond,...
        stat.mean_sign_cond,...
        stat.mean_sub_cond],...
        'gt angles, mean, conf.-interval (99%%, significantly (1%%) different from zero?, individual means');
% save standard deviation
gp_save([prefix, '_std.txt'], ...
        [gt,...
        stat.std_cond,...
        stat.std_conf_lower_cond,...
        stat.std_conf_upper_cond,...
        stat.std_sub_cond],...
        'gt angles, std, lower conf.-interval, upper conf.-interval, individual results')
